### ISSUE TITLE
Support for skipping synthesized symbols

### ISSUE THREAD

**Issue by franklinsch** [swiftlang/swift-docc-plugin#27]
#### Description:

The Swift compiler supports a `-skip-synthesized-members` argument which excludes synthesized symbols from symbol graph files. Synthesized symbols can lead to a large increase in number of documentation pages for some frameworks. We should have a way of generating documentation without synthesized symbols from the DocC plugin.

**Comment by ethan-kusters** [comment]
This would be a great first issue! To support this we would need to add support for parsing a new flag and then change the boolean we're passing here: https://github.com/apple/swift-docc-plugin/blob/main/Plugins/SharedPackagePluginExtensions/Target%2BdefaultSymbolGraphOptions.swift#L29

Here's an example of a custom flag the plugin currently supports: https://github.com/apple/swift-docc-plugin/blob/main/Sources/SwiftDocCPluginUtilities/PluginFlags/DisableIndexFlag.swift#L14.

Happy to help with any questions if anyone would like to take this on!

**Comment by natikgadzhi** [comment]
Was looking around for good small issues to get myself up to speed — looks like this one is complete in #28, @sofiaromorales 👏🏼 

@ethan-kusters, time to close this one? I would be happy to explore other issues and help out if I can, if you have anything that needs attention!
