### ISSUE TITLE
Warning when building a package using the plugin with Swift 5.9.

### ISSUE THREAD

**Issue by thomasvl** [swiftlang/swift-docc-plugin#65]
In adding Swift 5.9 to the CI for swift-protobuf, we noticed some warning coming from the plugin compile:

https://github.com/apple/swift-protobuf/actions/runs/6249612455/job/16966661520?pr=1459

```
/__w/swift-protobuf/swift-protobuf/main/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SharedPackagePluginExtensions/PackageExtensions.swift:31:17: warning: switch covers known cases, but 'TargetDependency' may have additional unknown values
                switch dependency {
                ^
/__w/swift-protobuf/swift-protobuf/main/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SharedPackagePluginExtensions/PackageExtensions.swift:31:17: note: handle unknown values using "@unknown default"
                switch dependency {
                ^
[1/1] Compiling plugin Swift-DocC
/__w/swift-protobuf/swift-protobuf/main/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Preview/Symbolic Links/SharedPackagePluginExtensions/PackageExtensions.swift:31:17: warning: switch covers known cases, but 'TargetDependency' may have additional unknown values
                switch dependency {
                ^
/__w/swift-protobuf/swift-protobuf/main/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Preview/Symbolic Links/SharedPackagePluginExtensions/PackageExtensions.swift:31:17: note: handle unknown values using "@unknown default"
                switch dependency {
                ^
```

### Checklist
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc-plugin/issues).

### Expected behavior
Clean compile.

### Actual behavior
Warning generated.

### Steps to Reproduce
Simply doing a build should produce the warnings.

### Swift-DocC Plugin Version Information

**Swift-DocC plugin version:** `1.3.0`
**Swift Compiler version:** 5.9

**Comment by d-ronnqvist** [comment]
This looks like it was already fixed by adding [`@unknown default` here](https://github.com/swiftlang/swift-docc-plugin/blob/main/Plugins/SharedPackagePluginExtensions/PackageExtensions.swift#L36-L37).
